package com.example.hoponuserservice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.springframework.data.annotation.Id;


@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Rider")
public class Rider {

    private String id;
    private String name;
    private String email;
    private String phoneNumber;
    private Location location;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "name")
    public String getName() {
        return name;
    }

    @DynamoDBAttribute(attributeName = "email")
    @NotNull
    public String getEmail() {
        return email;
    }

    @DynamoDBAttribute(attributeName = "phoneNumber")
    public String getPhoneNumber() {
        return phoneNumber;
    }

    @DynamoDBTypeConvertedJson
    @DynamoDBAttribute(attributeName = "location")
    public Location getLocation() {
        return location;
    }

}
